Laget generell lagringsfunksjon
navikt/fritak-agp-frontend pull request #41
Opened 2021-01-07 12:35 UTC by MrFjellstad

2021-01-07 12:57 UTC, laukvik requested changes

2021-01-07 12:57 UTC, laukvik commented on src/api/lagreData.ts
> +export interface responsdataInterface {
Synes vi burde ha stor bokstav på responsdataInterface siden det ikke er et verb.

2021-01-07 12:57 UTC, laukvik commented on src/api/lagreData.ts
> +      }, 10000);
Timeout verdien kunne vært et input parameter til koden som defaultet til 10 sekunder dersom det ikke var angitt?

2021-01-07 12:57 UTC, laukvik commented on src/api/lagreData.ts
> +const lagreData = async (
Denne metoden låser seg til POST kall. Synes navnet burde reflektere det også i tilfelle vi få flere kall. Hva med postData eller postAPI eller liknende?

2021-01-07 14:25 UTC, MrFjellstad commented on src/api/lagreData.ts
> +const lagreData = async (
Enig

2021-01-07 14:47 UTC, MrFjellstad commented on src/api/lagreData.ts
> +export interface responsdataInterface {
Endte opp med Responsdata siden det ble litt rart å postfiks med Interface etter å ha sett på den en stund

2021-01-08 08:55 UTC, laukvik approved these changes

2021-01-08 09:18 UTC, merged