Delete upload
navikt/fritak-agp-frontend pull request #63
Opened 2021-01-18 13:51 UTC by jafeld

2021-01-19 16:51 UTC, laukvik requested changes

2021-01-19 16:51 UTC, laukvik commented on src/components/gravid/GravidSide.tsx
> +    dispatchSkjema({ field: 'dokumentasjon', value: '' });
dispatchSkjema har blitt erstattet med dispatch. Gjorde det etter du lagde denne PR :-(

2021-01-19 16:51 UTC, laukvik commented on src/components/Upload.sass
>  .filknapp[disabled]
Sass klassene burde hete samme som komponentet. Ikke filknapp

2021-01-19 16:51 UTC, laukvik commented on src/components/Upload.tsx
> +      <label className='knapp filknapp'>
Synes at css klassen burde hete samme som komponentet: Upload

2021-01-19 16:51 UTC, laukvik commented on src/components/kronisk/KroniskReducer.ts
> +      nextState.dokumentasjon = payload?.dokumentasjon ?? undefined;
Er ikke "?? undefined" overflødig her?

2021-01-20 11:06 UTC, jafeld commented on src/components/Upload.sass
>  .filknapp[disabled]
Dette har jeg ikke endret på. Siste endring er fra laukvik :D

2021-01-20 11:07 UTC, jafeld commented on src/components/Upload.tsx
> +      <label className='knapp filknapp'>
Fikset

2021-01-20 11:43 UTC, laukvik approved these changes

2021-01-20 11:43 UTC, merged